name: forget-nothing
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: before
      run: |
        git checkout "$BEFORE"
        "${{ github.action_path }}/all-orgs.sh" > /tmp/before
      shell: bash
      env:
        BEFORE: ${{ github.event.pull_request.base.sha || github.event.before }}
    - name: after
      run: |
        git checkout "$AFTER"
        "${{ github.action_path }}/all-orgs.sh" > /tmp/after
      shell: bash
      env:
        AFTER:  ${{ github.event.pull_request.head.sha || github.event.after }}
    - name: diff
      run: |
        if [ -n "$(comm -23 /tmp/before /tmp/after)" ]; then
          comm -23 /tmp/before /tmp/after
          exit 1
        fi
      shell: bash
      